runtime: python37
entrypoint: gunicorn -b :$PORT main:app_server
# main refers to main.py, app_server refers to the variable for app.server inside that file 

handlers:
# Matches requests to /static/... to files in static/...
- url: /static
  static_dir: static
- url: /data
  static_dir: data

# instance_class: F2
# automatic_scaling:
#   target_cpu_utilization: 0.65
#   min_instances: 5
#   max_instances: 100
#   min_pending_latency: 30ms  # default value
#   max_pending_latency: automatic
#   max_concurrent_requests: 50

manual_scaling:
  instances: 4
resources:
  cpu: 16
  memory_gb: 2
  disk_size_gb: 2